use_frameworks!

platform :ios, '11.0'

target 'RCChatroomSceneKit_Example' do
  pod 'RCChatroomSceneKit', :path => '../'

  target 'RCChatroomSceneKit_Tests' do
    inherit! :search_paths

    
  end
end
